### ISSUE TITLE
Visual C++ exception message does not print, SIGABRT instead.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#11846]
Test code:
```nim
raise newException(IndexError, "hi there")
```

Correct (gcc C): 
```
nim c -r .\bug.nim
***\bug.nim(1) bug
Error: unhandled exception: hi there [IndexError]
```

Correct (gcc C++): 
```
nim cpp -r .\bug.nim
***\bug.nim(1) bug
Error: unhandled exception: hi there [IndexError]
```

Wrong (Visual C++)
```
nim cpp --cc:vcc -r .\bug.nim
***\bug.nim(1) bug
SIGABRT: Abnormal termination.
```

Nim version:
```
nim -v
Nim Compiler Version 0.20.99 [Windows: amd64]
Compiled at 2019-07-29
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by mratsim** [comment]
The whole C++ backend had this issue as raised in #6512, it was fixed by https://github.com/nim-lang/Nim/commit/c9f184401cb0a7289119c1785c3af032f9998ff8 but it seems like the fix only worked for GCC/Clang.

**Comment by treeform** [comment]
This is what I did to make it work:
 
```nim
setTerminate proc() {.noconv.} =
    # Remove ourself as a handler, reinstalling the default handler.
    setTerminate(nil)

    var msg = "Unknown error in unexpected exception handler"
    # try:
    #   raise
    # except Exception:
    #   msg = currException.getStackTrace() & "Error: unhandled exception: " &
    #     currException.msg & " [" & $currException.name & "]"
    # except StdException as e:
    #   msg = "Error: unhandled cpp exception: " & $e.what()
    # except:
    #   msg = "Error: unhandled unknown cpp exception"

    if currException != nil:
      msg = currException.getStackTrace() & "Error: unhandled exception: " &
        currException.msg & " [" & $currException.name & "]"

    when defined(genode):
      # stderr not available by default, use the LOG session
      echo msg
    else:
      writeToStdErr msg & "\n"

    quit 1
```
At https://github.com/nim-lang/Nim/blob/572b7c37a5e537ecf198b2761c7c0a7b2e2400f6/lib/system/excpt.nim#L486


I think the issue is that the 
```nim
try:
    raise
```

Just does not work with Visual C++ exceptions. But you can just look at the current exception if its there. I am not sure what this try-raise trying to do. I am confused by this.

**Comment by treeform** [comment]
Here is the issue what was being fixed by the regression: https://github.com/nim-lang/Nim/issues/10765

**Comment by nc-x** [comment]
Generating
```cpp
try {
  std::rethrow_exception(std::current_exception());
}
```
instead of
```cpp
try {throw;}
```
gives (on msvc)
```
Error: unhandled cpp exception: bad exception
```
which is again wrong.  (on gcc it again works).

<details><summary>Minimal C++ code for anybody who wants to investigate </summary>

```cpp
#include <exception>
#include <iostream>
using namespace std;

void x() {
  try {
    throw; // does not work in msvc
    // rethrow_exception(current_exception()); // works in msvc, but not for https://github.com/nim-lang/Nim/issues/11846
  } catch (...) {
    cout << "Called by terminate." << endl;
  }
  exit(-1);
}

int main() {
  try {
    set_terminate(x);
    throw 1;
  } catch (string) {
    cout << "ABC" << endl;
  }
  return 0;
}

```
</details>

**Comment by cooldome** [comment]
fixed

**Comment by treeform** [comment]
@cooldome Still not fixed for me. I get the exception stack trace but not the message. :(

**Comment by treeform** [comment]
This change here fixes it:

```nim
    {.emit"#if defined(_MSC_VER) && (_MSC_VER < 1923)".}
    #msg = "Error: unhandled unknown cpp exception"
    msg = currException.getStackTrace() & "Error: unhandled exception: " &
        currException.msg & " [" & $currException.name & "]"
    {.emit"#endif".}
```

**Comment by treeform** [comment]
I have updated to the newer visual VC++ and that works as well. I guess we are laving older VC++ in broken state but that's probably fine.
