### ISSUE TITLE
[ARC] Undeclared variable in C with inline pragma and iterators

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14251]
This code produces a C compiler error message with ARC. Found in https://github.com/nitely/nim-regex from https://github.com/citycide/glob. Maybe related to https://github.com/nim-lang/Nim/issues/14219 (although https://github.com/nim-lang/Nim/pull/14225 didn't fix it for me).

### Example
```nim
# a.nim
import b

for path in walkGlob("src"):
  echo path

# b.nim
type
  NodeKind = enum
    reChar
    
  Node = object
    kind: NodeKind
    shorthands: seq[Node]

func match(n: Node): bool {.inline.} = # inline is important
  case n.kind
  of reChar:
    for nn in n.shorthands:
      let matches = nn.match()
      if matches: break
  else:
    discard
  true

func matchImpl(): bool {.inline.} = # here too
  match(Node())

proc contains(s: string): bool {.inline.} = # and here
  result = matchImpl()

proc hasMagic(str: string): bool =
  str.contains()

iterator walkGlob*(pattern: string): string =
  var proceed = pattern.hasMagic

  if proceed:
    echo contains("hello")
```

### Current Output
```
/home/dian/.cache/nim/daf_r/@mdaf.nim.c: In function 'match__VJAfeKGRtAwhM7dlrQGhignodematch':
/home/dian/.cache/nim/daf_r/@mdaf.nim.c:167:37: error: 'nn' undeclared (first use in this function); did you mean 'n'?
  167 |      eq___9b4oYSLik5J1HZpxMHmD5NA((&nn), n.shorthands.p->data[i]);
      |                                     ^~
      |    
```

### Expected Output
```
true
```

```
$ nim -v
Nim Compiler Version 1.3.1 [Linux: amd64]
Compiled at 2020-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b8e6ea7547344389b5e45c3af249fee9642f028e
active boot switches: -d:release
```

**Comment by cooldome** [comment]
I confirm this one is not related to #14219. It is an issue with inline handling. Injectdestructors corrupts input AST such that following transformations get AST without `nn` variable declarations. Multiple transformations happen only for inlined procs.

**Comment by cooldome** [comment]
Looks like the issue has been fixed, I can't replicate it anymore

**Comment by ghost** [comment]
True, this code works now, closing.

**Comment by ghost** [comment]
Although the glob issue is still there, will try to reproduce it :P
