### ISSUE TITLE
big decimal literals not working

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#1429]
``` nimrod
echo 0b11111111_11111111_11111111_11111111_11111111_11111111_11111111_11111111'u64
echo 0o7777_7777_7777_7777_7777_7777_7777_7777'u64
echo 0xFF_FF_FF_FF_FF_FF_FF_FF'u64
echo 18446744073709551615'u64
```

The first three work, the last doesn't, even though all are the same number.

Would an integration of BigInts in the language be the way to solve this? I have a library for them: https://github.com/def-/bigints
But they're not stable yet and use term rewritings to avoid copying.

**Comment by skyfex** [comment]
This pull request will fix most of this: https://github.com/Araq/Nim/pull/1960

Except the "# This should work without the literal" stuff.. that is unfortunately not easily possible, unless we integrated bigints into the core library and compiler. I'm a big fan of that idea though. It would be neat if huge int literals became bigints instead of just failing.

**Comment by def-** [comment]
Looks like only these two problems remain, when specified without the unsigned literal:

```nimrod
import unsigned

var
  u32: uint32
  u64: uint64

u32 = 3000000000
u64 = 10000000000000000000
```

```
a.nim(7, 6) Error: type mismatch: got (int64) but expected 'uint32'
a.nim(8, 6) Error: number 10000000000000000000 out of valid range
```

**Comment by johnnovak** [comment]
I have managed to trigger yet another different error message in addition to the above when dealing with the same issue :)

```
var u64: uint64 = 0xffffffffffffffff
# Error: type mismatch: got (int literal(-1)) but expected 'uint64'
```

**Comment by dom96** [comment]
I guess https://github.com/nim-lang/Nim/pull/2890 didn't quite fix this?

**Comment by Yardanico** [comment]
@dom96 , @Araq close? original issue is fixed

**Comment by johnnovak** [comment]
@Yardanico These tests are still failing, tested with devel branch nim right now.

Test 1

```nim
var
  u32: uint32
  u64: uint64

u32 = 3000000000
u64 = 10000000000000000000

a.nim(7, 6) Error: type mismatch: got (int64) but expected 'uint32'
a.nim(8, 6) Error: number 10000000000000000000 out of valid range
```

Test 2

```nim
var u64: uint64 = 0xffffffffffffffff
# Error: type mismatch: got (int literal(-1)) but expected 'uint64'
```

**Comment by Araq** [comment]
These tests are not supposed to work. The type of an integer literal is ``int`` unless it doesn't fit 32bits in which case it is an ``int64`` (somebody needs to patch the manual to mention this fact -.- )
