### ISSUE TITLE
differenct nim-glm code

### ISSUE THREAD

**Issue by getfile** [nim-lang/Nim#24524]
### Description

The nim-glm library I downloaded from https://github.com/stavenko/nim-glm.
    The number of lines in the vec.nim file is: 694. The `distance` function in the file is: 
    `proc distance*[N,T](v1,v2: Vec[N,T]): T {.inline, noinit.} = length(v2 - v1)`

And the nim-glm library that I installed using nimble install glm.
    The number of lines in the file vec.nim is: 685, and the `distance` function in the file is: 
    `proc distance*[N,T](v1,v2: Vec[N,T]): Vec[N,T] = length(v2 - v1)`
    This is obviously wrong

The version of both is glm 1.1.1.

Why is the code for the nimble install different from the github code?

My nim installation is version 2.0.10.

### Nim Version

nim 2.0.10

**Comment by metagn** [comment]
Nimble handles versions via git tag. The last tag on that repo for 1.1.1 was on [July 2018](https://github.com/stavenko/nim-glm/releases/tag/v1.1.1), since which there have been commits. To install the latest git version and bypass the tag, install via `nimble install packagename@#HEAD`, similarly in the .nimble file `requires "packagename#HEAD"`. See https://nim-lang.github.io/nimble/use-packages.html#nimble-install and https://nim-lang.github.io/nimble/create-packages.html#dependencies

**Comment by getfile** [comment]
Yes, as you said, the problem is solved. 
The main problem is in the glm library, which has been confusing me for some time.

**Comment by metagn** [comment]
So is there still an issue? Have you tried `nimble install glm@#HEAD` as mentioned?

**Comment by getfile** [comment]
> So is there still an issue? Have you tried `nimble install glm@#HEAD` as mentioned?

Yeah, the way you said it, problem solved.
I'll close the thread.
