### ISSUE TITLE
[Codegen] {.global.} does not work.

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#2488]
var marked {.global.} will effectively be local in JS.

``` nim
proc test() =
    var i {.global.} = 0
    echo i
    inc i
test()
```

``` js
function test_15003() {
var i_15005 = [0];
rawEcho(cstrToNimstr((i_15005[0])+""));
i_15005[0] = addInt(i_15005[0], 1);
}
```

I guess it's low priority but still worth mentioning.

**Comment by alehander42** [comment]
This is fixed by https://github.com/nim-lang/Nim/pull/8962 :D

**Comment by andreaferretti** [comment]
Worth mentioning (I was confused): that PR was closed, hence this issue still fails

**Comment by alehander42** [comment]
ah, it's not merged indeed: sorry
