### ISSUE TITLE
[times.nim] Timezone offset gives no indication of +/-

### ISSUE THREAD

**Issue by jonathonf** [nim-lang/Nim#3200]
## Summary

The timezone offset provided by `getLocalTime()` and `getGMTime()` provide only a 'plain' hour instead of indicating whether the timezone is ahead or behind of UTC/GMT. This is counter to the [documentation](http://nim-lang.org/docs/times.html#format,TimeInfo,string) which suggests +/- should be present for `z`, `zz`, and `zzz`.

See also #3199.
## nim test code

``` nim
import times

echo getTzname()
echo getTime().getGMTime.format("zzz")
echo getTime().getLocalTime.format("zzz")
```
## Output, BST

http://www.timeanddate.com/time/zones/bst

| Code | Actual | Expected |
| --- | --- | --- |
| `getTzname()` | (nonDST: GMT, DST: BST) | (nonDST: GMT, DST: BST) |
| `getTime().getGMTime.format("zzz")` | 00:00 | +00:00 |
| `getTime().getLocalTime.format("zzz")` | 00:00 | +01:00 |
## Output, EDT

http://www.timeanddate.com/time/zones/edt

| Code | Actual | Expected |
| --- | --- | --- |
| `getTzname()` | (nonDST: EST, DST: EDT) | (nonDST: EST, DST: EDT) |
| `getTime().getGMTime.format("zzz")` | 00:00 | +00:00 |
| `getTime().getLocalTime.format("zzz")` | 05:00 | -04:00 |

**Comment by GULPF** [comment]
Looks like this is fixed. `getTime().getGMTime.format("zzz")` now gives +00:00.

**Comment by andreaferretti** [comment]
I am not sure how to test this (how to temporarily change the timezone on the command line). If it is confirmed to be fixed, I can close it

**Comment by niv** [comment]
The `TZ` trick at least doesn't seem to work with nim and I don't think this is fixed?

On my system (CEST) it still gives a offset of +0 (see the last two commands), but it should be +0200.

```
tmp → cat tz.nim
import times
echo getTimezone(), ": ", getTime().getGMTime.format("zzz")

tmp → nim -v
Nim Compiler Version 0.17.2 (2017-09-07) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 811fbdafd958443ddac98ad58c77245860b38620
active boot switches: -d:release

tmp → TZ=UTC date
Tue Oct  3 15:41:20 UTC 2017

tmp → TZ=UTC ./tz
0: +00:00

tmp → TZ=US/Pacific date
Tue Oct  3 08:41:26 PDT 2017

tmp → TZ=US/Pacific ./tz
0: +00:00

tmp → date
Tue Oct  3 17:44:23 CEST 2017

tmp → ./tz
0: +00:00
```

**Comment by GULPF** [comment]
Are you using latest devel? `getTimezone()` was broken until https://github.com/nim-lang/Nim/pull/6466.

**Comment by GULPF** [comment]
This can be closed, tests exists in ttimes.nim.
