### ISSUE TITLE
JS backend doesn't like building seqs recursively

### ISSUE THREAD

**Issue by sid-code** [nim-lang/Nim#4883]
The following code works fine when compiled normally, but gives an error in the JS backend.

``` nim
type
  AKind = enum Str, AList
  A = object # represents an tree of arbirary arity
    case kind: AKind:
      of Str: a: string
      of AList: b: seq[A]

# walks the tree and returns all leaves in a seq
proc recurse(a: A): seq[A] =
  newSeq(result, 0)
  case a.kind:
    of Str:
      result.add(a)
    of AList:
      for innerA in a.b:
        result.add(recurse(innerA))

var d = A(kind: AList, b: @[
          A(kind: Str, a: "hi world"),
          A(kind: AList, b: @[A(kind: Str, a: "hello")])])
discard recurse(d)
```

The error looks like this:

```
test.js:315 Uncaught TypeError: Cannot read property 'kind' of undefined
```

This could be related to #4139.

**Comment by sid-code** [comment]
Here's what I could find about what might be causing the error. The following code is the `recurse` proc modified to print out the object at index 0 of `a`.

```nim
proc recurse(a: A): seq[A] =
  newSeq(result, 0)
  case a.kind:
    of Str:
      result.add(a)
      asm """
      console.log(`a`[0]);
      """

    of AList:
      for innerA in a.b:
        result.add(recurse(innerA))
```

This should print out some object but instead it just prints out `undefined`.

**Comment by sid-code** [comment]
Some more details:

- defining `A` as `ref object` instead of `object` removes the error but not the issue, as `undefined` still gets printed in the second example
- simply creating a `seq[A]` and adding an object to it works fine, it seems to be tied to the `result` variable

**Comment by andreaferretti** [comment]
I cannot reproduce this. @sid-code can you tell whether this is now fixed for you?

**Comment by sid-code** [comment]
Yes, it still happens.

```
Nim Compiler Version 0.17.0 (2017-06-25) [Linux: amd64]             
Copyright (c) 2006-2017 by Andreas Rumpf                            

git hash: 2b8a1cee8cbeddb3e64193a59a78b5d0f46d2fda                  
active boot switches: -d:release -d:useLinenoise -d:nativeStackTrace          
```

I run `nim js test.nim` and then `node nimcache nimcache/test.js` or load it in a browser via the `<script>` tag. This causes the error I posted above.

**Comment by andreaferretti** [comment]
You are right, I was too quick. It seems to be broken on v0.17, but it is fixed on devel.

I am closing it since it is now fixed, but feel free to reopen in case
