### ISSUE TITLE
link failure when swith c to cpp to c

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#5219]
```
nim c -f somefile.nim
nim cpp somefile.nim
nim c somefile.nim
```

linking works again if force the last compile
```nim c -f somefile.nim```

Issue is on win and linux (at least)

**Comment by Araq** [comment]
Yeah, nim should probably generate ``.cpp.obj`` files. Too bad that external tools depend on how the names are produced.

**Comment by jlp765** [comment]
Is it worth checking xxxxx.json (or something) to determine if the object files need to be recreated because the previous compilation was the other type?

I note that if the order is cpp/c/cpp then it links without error, unless the .o files only are deleted.
(of course, deleting obj files shouldn't happen in the normal order of things)

**Comment by andreaferretti** [comment]
Doesn't seem to affect MacOS

**Comment by dom96** [comment]
Maybe it was fixed already?

**Comment by Yardanico** [comment]
@dom96 it still fails for me on Arch Linux with both GCC 8.1 and Clang 6.0

**Comment by nc-x** [comment]
Works fine now. Fixed by https://github.com/nim-lang/Nim/pull/8278
