### ISSUE TITLE
nimsuggest -h doesn't shows nimsuggest specific documentation

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7514]
nimsuggest -h|grep stdin
empty

`nimsuggest -h` just shows same as `nim -h`

it should show https://github.com/nim-lang/Nim/blob/devel/nimsuggest/nimsuggest.nim#L29 and/or link to https://nim-lang.org/docs/nimsuggest.html

**Comment by Yardanico** [comment]
https://github.com/nim-lang/Nim/issues/5841
It was already fixed, no?

**Comment by timotheecour** [comment]
upon further inspeciton, looks like still buggy:

nim == nim -h == nim --help

nimsuggest #ok
nimsuggest --help #ok
nimsuggest -h # BAD

**Comment by GULPF** [comment]
Fixed by #7515
